on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: test
        run: |
          cd app && go test -race -v -mod=readonly -timeout=60s -covermode=atomic ./...
      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.49.0
      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --config .golangci.yml ./...
      - name: build
        run: cd app && go build -race -v -mod=readonly
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref}}
        run: | # log into docker hub account
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
      - name: build and push master image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker build -t ghcr.io/pechorka/bot-template:master .
          docker push ghcr.io/pechorka/bot-template:master
      - name: deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          curl http://165.227.148.183:8080/update/echo-bot/${{secrets.UPDATER_KEY}}