name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: set up go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: test
        run: |
          cd app && go test -race -v -mod=readonly -timeout=60s -covermode=atomic ./...
      - name: install golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.49.0
      - name: run linters
        run: $GITHUB_WORKSPACE/golangci-lint run --config .golangci.yml ./...
      - name: build
        run: cd app && go build -race -v -mod=readonly
      - name: build and push master image
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker build -t pechorka/bot-template:master .
          docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
          docker push pechorka/bot-template:master